# Generated by Django 2.2 on 2020-08-28 07:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
